# Generated by Django 5.2.4 on 2025-07-22 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0004_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_resident', models.BooleanField(default=False)),
                ('subscription_until', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to='content.contentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'content')},
            },
        ),
    ]
