# Generated by Django 5.2.4 on 2025-07-22 14:21

import content.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Краткое описание контента', null=True)),
                ('content_type', models.CharField(choices=[('video', '🎥 Видео'), ('audio', '🎧 Аудио'), ('file', '📄 Файл')], max_length=10)),
                ('telegram_url', models.URLField(help_text='Ссылка на сообщение в Telegram')),
                ('duration', models.CharField(help_text='Например: 00:00:45', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, help_text='Только для видео. Макс. 2 МБ', null=True, upload_to='thumbnails/', validators=[content.validators.validate_file_size])),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contentitem')),
            ],
            options={
                'unique_together': {('telegram_id', 'content_item')},
            },
        ),
    ]
