# Generated by Django 5.2.4 on 2025-07-21 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', '🎥 Видео'), ('audio', '🎧 Аудио'), ('file', '📄 Файл')], max_length=10)),
                ('telegram_url', models.URLField(help_text='Ссылка на сообщение в Telegram')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.genre')),
            ],
        ),
    ]
