# Generated by Django 5.2.4 on 2025-07-21 10:05

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='duration',
            field=models.CharField(default='00:00:00', help_text='Например: 00:00:45', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Только для видео. Макс. 2 МБ', null=True, upload_to='thumbnails/', validators=[content.validators.validate_file_size]),
        ),
    ]
