# Generated by Django 5.2.4 on 2025-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('subscription_status', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
                ('subscription_until', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
