# Generated by Django 5.2.4 on 2025-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentitem_duration_contentitem_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Краткое описание контента', null=True),
        ),
    ]
