# Generated by Django 5.2.4 on 2025-09-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='kind',
            field=models.CharField(choices=[('default', 'Обычный жанр'), ('special', 'Спецжанр (с группами)')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.genre'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Краткое описание', null=True),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='content.genre')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.group'),
        ),
    ]
